config/routes.rb
Rails.application.routes.draw do
  resources :apartaments
  
 get '/articles', to:'articles#index'
 root 'articles#index'
end

app/models/apartament.rb
class Apartament < ApplicationRecord
    has_one_attached :foto
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/apartaments_controller.rb
class ApartamentsController < ApplicationController
  before_action :set_apartament, only: %i[ show edit update destroy ]

  # GET /apartaments or /apartaments.json
  def index
    @apartaments = Apartament.all
  end

  # GET /apartaments/1 or /apartaments/1.json
  def show
  end

  # GET /apartaments/new
  def new
    @apartament = Apartament.new
  end

  # GET /apartaments/1/edit
  def edit
  end

  # POST /apartaments or /apartaments.json
  def create
    @apartament = Apartament.new(apartament_params)

    respond_to do |format|
      if @apartament.save
        format.html { redirect_to apartament_url(@apartament), notice: "Apartament was successfully created." }
        format.json { render :show, status: :created, location: @apartament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apartament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartaments/1 or /apartaments/1.json
  def update
    respond_to do |format|
      if @apartament.update(apartament_params)
        format.html { redirect_to apartament_url(@apartament), notice: "Apartament was successfully updated." }
        format.json { render :show, status: :ok, location: @apartament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apartament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartaments/1 or /apartaments/1.json
  def destroy
    @apartament.destroy

    respond_to do |format|
      format.html { redirect_to apartaments_url, notice: "Apartament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartament
      @apartament = Apartament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apartament_params
      params.require(:apartament).permit(:titolo, :luogo, :piscina, :bagno, :vista_mare, :cucina, :foto)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/helpers/apartaments_helper.rb
module ApartamentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/apartaments/_apartament.html.erb
<div id="<%= dom_id apartament %>">

  <% if apartament.foto.attached? %>
    <%= image_tag url_for(apartament.foto), class: 'w-100', style: 'max-width: 500px;' %>
  <% end %>


  <p>
    <strong>Titolo:</strong>
    <%= apartament.titolo %>
  </p>

  <p>
    <strong>Luogo:</strong>
    <%= apartament.luogo %>
  </p>

  <p>
    <strong>Piscina:</strong>
    <%= apartament.piscina %>
  </p>

  <p>
    <strong>Bagno:</strong>
    <%= apartament.bagno %>
  </p>

  <p>
    <strong>Vista mare:</strong>
    <%= apartament.vista_mare %>
  </p>

  <p>
    <strong>Cucina:</strong>
    <%= apartament.cucina %>
  </p>

</div>

app/views/apartaments/_form.html.erb
<div class="container-fluid">
  <%= form_with(model: apartament) do |form| %>
    <% if apartament.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(apartament.errors.count, "error") %> prohibited this apartament from being saved:</h2>

        <ul>
          <% apartament.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :titolo, class: 'from-label' %>
      <%= form.text_area :titolo, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :luogo, class: 'from-label' %>
      <%= form.text_area :luogo, class: 'form-control' %>
    </div>

  
    <div>
      <%= form.label :bagno, class: 'from-label' %>
      <%= form.text_area :bagno, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :cucina, class: 'from-label' %>
      <%= form.text_area :cucina, class: 'form-control' %>
    </div>

    <div>
    <%= form.label :vista_mare, class: 'from-label' %>
    <%= form.check_box :vista_mare, class: 'form-check' %>
  </div>
    
    <div>
      <%= form.label :piscina, class: 'from-label' %>
      <%= form.check_box :piscina, class: 'form-check' %>
    </div>

    <div class="mb-3">
    <%= form.label :foto, class: 'form-label' %>
    <%= form.file_field :foto, class: 'form-control' %>
  </div>


    <div>
      <%= form.submit 'Salva', class: 'btn btn-primary w-100' =%>
    </div>
  <% end %>
</div>

app/views/apartaments/edit.html.erb
<div class="container">
  <h1>Modifica appartamento</h1>

  <%= render "form", apartament: @apartament %>

  <br>

  <div>
    <%= link_to "Visualizza l'appartamento", @apartament , class:'btn btn-success w-100'%> 
    <h1>  </h1>
    <%= link_to "Torna agli appartamenti", apartaments_path, class:'btn btn-secondary w-100' %>
  </div>
</div>

app/views/apartaments/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  
  <h1>Appartamenti</h1>

  <%= link_to "Nuovo appartamento", new_apartament_path, class: 'btn btn-warning w-100' %>

  <div id="apartaments" class="row">
    <% @apartaments.each do |apartament| %>
      <div class="col-4">
        <%= render apartament %>
        <p>
          <%= link_to "Dettagli", apartament, class: 'btn btn-primary w-100' %>
        </p>
      </div>
    <% end %>
  </div>

</div>

app/views/apartaments/new.html.erb
<div class="container"> 
 <h1>New apartament</h1>

  <%= render "form", apartament: @apartament %>

  <br>

  <div>
    <%= link_to "Torna alle offerte", apartaments_path, class:'btn btn-secondary w-100' %>
  </div>
</div>

app/views/apartaments/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @apartament %>

  <div>
    <%= link_to "Modifica", edit_apartament_path(@apartament), class:'btn btn-warning w-100' %> 
     
    <%= button_to "Ellimina", @apartament, method: :delete, class:'btn btn-danger w-100' %> 

    <%= link_to "Torna agli appatamenti", apartaments_path, class:'btn btn-secondary w-100'%>  

    
  </div>
</div>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="it">
<html>
  <head>
    <meta charset="utf-8">
    <title>Job</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <%= render 'layouts/carousel' %>
  <%= render 'layouts/calendar' %>
  </body>
</html>

app/views/layouts/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://www.appartamentimisano.it/wp-content/uploads/2016/10/MG_7572-2000x800.jpg" class="d-block w-100" alt="Immagine non disponibile">
    </div>
    <div class="carousel-item">
      <img src="https://www.lapalmaaulac.com/fileadmin/_processed_/b/6/csm_APP5_2a0eca5f57.jpg" class="d-block w-100" alt="Immagine non disponibile">
    </div>
    <div class="carousel-item">
      <img src="https://www.rossiduilio.com/img/render-sito.jpg" class="d-block w-100" alt="Immagine non disponibile">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Precedente</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Successiva</span>
  </button>
</div>
    <ol></ol>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/index.html.erb">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:3002/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:3002/apartaments">Ricerca immobili</a>
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
<html>
  <head>
    <meta charset="utf-8">
    <title>Job</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>

    <%= render 'layouts/footer' %>


    
  </body>
</html>